<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'البؤساء',
                'author' => 'فيكتور هيجو',
                'isbn' => '978-1234567890',
                'publisher' => 'دار النشر العربي',
                'pages' => 1488,
                'category' => 'روايات',
                'price' => 200.00,
                'discount_price' => 150.00,
                'description' => 'رواية البؤساء من أعظم روايات القرن التاسع عشر، تحكي قصة جان فالجان وكفاحه من أجل الحرية والكرامة الإنسانية. تصور الرواية المجتمع الفرنسي في تلك الحقبة بكل تناقضاته.',
                'cover_image' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
                'stock' => 15,
                'status' => 'available',
                'rating' => 4.8,
                'reviews_count' => 245,
            ],
            [
                'title' => 'الحرب والسلام',
                'author' => 'ليو تولستوي',
                'isbn' => '978-9876543210',
                'publisher' => 'دار الكتاب العالمي',
                'pages' => 1225,
                'category' => 'روايات',
                'price' => 250.00,
                'discount_price' => 200.00,
                'description' => 'رواية ملحمية تدور أحداثها خلال الغزو الفرنسي لروسيا، تتناول قصص خمس عائلات أرستقراطية روسية.',
                'cover_image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
                'stock' => 12,
                'status' => 'available',
                'rating' => 4.7,
                'reviews_count' => 189,
            ],
            [
                'title' => 'مئة عام من العزلة',
                'author' => 'غابرييل غارسيا ماركيز',
                'isbn' => '978-5555555555',
                'publisher' => 'دار الآداب',
                'pages' => 417,
                'category' => 'روايات',
                'price' => 180.00,
                'discount_price' => 135.00,
                'description' => 'رواية تحكي قصة عائلة بوينديا عبر سبعة أجيال في قرية ماكوندو الخيالية، وهي من روائع الواقعية السحرية.',
                'cover_image' => 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400',
                'stock' => 20,
                'status' => 'available',
                'rating' => 4.9,
                'reviews_count' => 312,
            ],
            [
                'title' => 'أصل الأنواع',
                'author' => 'تشارلز داروين',
                'isbn' => '978-1111111111',
                'publisher' => 'دار العلوم',
                'pages' => 502,
                'category' => 'علمية',
                'price' => 160.00,
                'discount_price' => null,
                'description' => 'الكتاب الذي غير نظرتنا للحياة، يقدم نظرية التطور بالانتقاء الطبيعي.',
                'cover_image' => 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400',
                'stock' => 8,
                'status' => 'available',
                'rating' => 4.6,
                'reviews_count' => 156,
            ],
            [
                'title' => 'موجز تاريخ الزمن',
                'author' => 'ستيفن هوكينج',
                'isbn' => '978-2222222222',
                'publisher' => 'دار الفيزياء الحديثة',
                'pages' => 256,
                'category' => 'علمية',
                'price' => 140.00,
                'discount_price' => 120.00,
                'description' => 'رحلة مذهلة في عالم الفيزياء الكونية، من الانفجار الكبير إلى الثقوب السوداء.',
                'cover_image' => 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400',
                'stock' => 25,
                'status' => 'available',
                'rating' => 4.7,
                'reviews_count' => 201,
            ],
            [
                'title' => 'تاريخ الحضارات',
                'author' => 'ويل ديورانت',
                'isbn' => '978-3333333333',
                'publisher' => 'دار التاريخ',
                'pages' => 890,
                'category' => 'تاريخية',
                'price' => 300.00,
                'discount_price' => null,
                'description' => 'موسوعة شاملة تتناول تاريخ الحضارات الإنسانية من العصور القديمة حتى العصر الحديث.',
                'cover_image' => 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400',
                'stock' => 5,
                'status' => 'available',
                'rating' => 4.8,
                'reviews_count' => 98,
            ],
            [
                'title' => 'فن الحرب',
                'author' => 'سون تزو',
                'isbn' => '978-4444444444',
                'publisher' => 'دار الحكمة الشرقية',
                'pages' => 273,
                'category' => 'فلسفة',
                'price' => 90.00,
                'discount_price' => 70.00,
                'description' => 'كتاب عسكري صيني كلاسيكي، يتناول استراتيجيات الحرب والصراع، ويُطبق في مجالات الأعمال والإدارة.',
                'cover_image' => 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400',
                'stock' => 30,
                'status' => 'available',
                'rating' => 4.5,
                'reviews_count' => 432,
            ],
            [
                'title' => 'ذاكرة الجسد',
                'author' => 'أحلام مستغانمي',
                'isbn' => '978-6666666666',
                'publisher' => 'دار الأدب العربي',
                'pages' => 348,
                'category' => 'روايات',
                'price' => 120.00,
                'discount_price' => 95.00,
                'description' => 'رواية عربية شهيرة تحكي قصة حب ومعاناة رسام جزائري فقد ذراعه في الثورة.',
                'cover_image' => 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
                'stock' => 18,
                'status' => 'available',
                'rating' => 4.4,
                'reviews_count' => 267,
            ],
            [
                'title' => 'السيرة النبوية',
                'author' => 'ابن هشام',
                'isbn' => '978-7777777777',
                'publisher' => 'دار الكتب الإسلامية',
                'pages' => 654,
                'category' => 'دينية',
                'price' => 170.00,
                'discount_price' => null,
                'description' => 'سيرة النبي محمد صلى الله عليه وسلم، من أهم المصادر التاريخية الإسلامية.',
                'cover_image' => 'https://images.unsplash.com/photo-1609220136736-443140cffec6?w=400',
                'stock' => 22,
                'status' => 'available',
                'rating' => 4.9,
                'reviews_count' => 512,
            ],
            [
                'title' => 'الخيميائي',
                'author' => 'باولو كويلو',
                'isbn' => '978-8888888888',
                'publisher' => 'دار الحكمة',
                'pages' => 197,
                'category' => 'روايات',
                'price' => 110.00,
                'discount_price' => 85.00,
                'description' => 'رواية رمزية عن راعي أندلسي يسافر بحثاً عن كنز، ويكتشف أن الكنز الحقيقي يكمن في الرحلة نفسها.',
                'cover_image' => 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400',
                'stock' => 35,
                'status' => 'available',
                'rating' => 4.6,
                'reviews_count' => 389,
            ],
            [
                'title' => 'العادات السبع للناس الأكثر فعالية',
                'author' => 'ستيفن كوفي',
                'isbn' => '978-9999999999',
                'publisher' => 'دار التنمية البشرية',
                'pages' => 381,
                'category' => 'تطوير ذاتي',
                'price' => 130.00,
                'discount_price' => null,
                'description' => 'كتاب في التنمية الذاتية يقدم سبع عادات أساسية للنجاح الشخصي والمهني.',
                'cover_image' => 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400',
                'stock' => 40,
                'status' => 'available',
                'rating' => 4.7,
                'reviews_count' => 456,
            ],
            [
                'title' => 'الأمير',
                'author' => 'نيكولو مكيافيلي',
                'isbn' => '978-1010101010',
                'publisher' => 'دار الفلسفة السياسية',
                'pages' => 142,
                'category' => 'فلسفة',
                'price' => 80.00,
                'discount_price' => 65.00,
                'description' => 'كتاب سياسي كلاسيكي يتناول قواعد الحكم والسلطة، ويعد من أهم كتب الفلسفة السياسية.',
                'cover_image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
                'stock' => 0,
                'status' => 'out_of_stock',
                'rating' => 4.3,
                'reviews_count' => 178,
            ],
            [
                'title' => 'الجريمة والعقاب',
                'author' => 'فيودور دوستويفسكي',
                'isbn' => '978-1212121212',
                'publisher' => 'دار الأدب الروسي',
                'pages' => 671,
                'category' => 'روايات',
                'price' => 190.00,
                'discount_price' => 145.00,
                'description' => 'رواية نفسية فلسفية تحكي قصة طالب فقير يرتكب جريمة قتل ويعاني من تبعاتها النفسية.',
                'cover_image' => 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
                'stock' => 10,
                'status' => 'available',
                'rating' => 4.8,
                'reviews_count' => 298,
            ],
            [
                'title' => 'الذكاء العاطفي',
                'author' => 'دانيال جولمان',
                'isbn' => '978-1313131313',
                'publisher' => 'دار علم النفس',
                'pages' => 384,
                'category' => 'تطوير ذاتي',
                'price' => 145.00,
                'discount_price' => null,
                'description' => 'كتاب رائد يشرح أهمية الذكاء العاطفي في النجاح الشخصي والمهني.',
                'cover_image' => 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400',
                'stock' => 28,
                'status' => 'available',
                'rating' => 4.5,
                'reviews_count' => 334,
            ],
            [
                'title' => 'قصة الحضارة الإسلامية',
                'author' => 'راغب السرجاني',
                'isbn' => '978-1414141414',
                'publisher' => 'دار التراث الإسلامي',
                'pages' => 520,
                'category' => 'تاريخية',
                'price' => 210.00,
                'discount_price' => 170.00,
                'description' => 'عرض شامل لتاريخ الحضارة الإسلامية وإنجازاتها في مختلف المجالات.',
                'cover_image' => 'https://images.unsplash.com/photo-1585779034823-7e9ac8faec70?w=400',
                'stock' => 0,
                'status' => 'coming_soon',
                'rating' => 0,
                'reviews_count' => 0,
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
